# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=12, unique=True)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=8)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_phone', models.CharField(db_index=True, max_length=15)),
                ('lead_email', models.EmailField(blank=True, default='', max_length=254)),
                ('seats', models.PositiveSmallIntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, max_length=22)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('operator', 'Operator'), ('admin', 'Admin'), ('system', 'System')], default='', max_length=10)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingTraveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('is_lead', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'booking_travellers',
            },
        ),
    ]
