# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='inventory.departure'),
        ),
        migrations.AddField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtraveller',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['operator', '-created_at'], name='bookings_operato_769cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['departure', 'status'], name='bookings_departu_eb3148_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('seats__gte', 1), ('seats__lte', 80)), name='booking_seats_range'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('base_amount'), '+', models.F('convenience_fee')))), name='total_is_base_plus_fee'),
        ),
        migrations.AddConstraint(
            model_name='bookingtraveller',
            constraint=models.UniqueConstraint(condition=models.Q(('is_lead', True)), fields=('booking',), name='one_lead_per_booking'),
        ),
    ]
