# Generated by Django 5.2.17 on 2026-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_code_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_token',
            field=models.CharField(blank=True, max_length=43, null=True, unique=True),
        ),
    ]
