# Generated by Django 5.2.17 on 2026-10-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_traveller_site'),
        ('payments', '0003_transfer_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.payout'),
        ),
    ]
