# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='package',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.city'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['from_city', 'to_city', 'status'], name='packages_from_ci_54b232_idx'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('nights__lte', 15)), name='nights_0_15'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_person__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('default_seats__gte', 1), ('default_seats__lte', 80)), name='default_seats_1_80'),
        ),
    ]
