# Generated by Django 5.2.17 on 2026-10-02 17:57

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meals', 'Meals'), ('accommodation', 'Accommodation'), ('transport', 'Transport'), ('activities', 'Activities'), ('places', 'Visiting places'), ('other', 'Other')], max_length=15)),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='catalog.package')),
            ],
            options={
                'db_table': 'package_facilities',
                'ordering': ['category', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('package', 'category', 'label'), name='unique_facility_per_package')],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.package_image_path)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.package')),
            ],
            options={
                'db_table': 'package_images',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('package',), name='one_cover_per_package')],
            },
        ),
    ]
