# Generated by Django 5.2.17 on 2026-10-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_images_and_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickup_point',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='catalog.package')),
            ],
            options={
                'db_table': 'package_itinerary_days',
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('package', 'day_number'), name='one_row_per_day')],
            },
        ),
    ]
