# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('held_seats', models.PositiveSmallIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='catalog.package')),
            ],
            options={
                'db_table': 'departures',
                'ordering': ['departure_date'],
                'indexes': [models.Index(fields=['departure_date', 'status'], name='departures_departu_15b676_idx')],
                'constraints': [models.UniqueConstraint(fields=('package', 'departure_date'), name='one_departure_per_day'), models.CheckConstraint(condition=models.Q(('total_seats__gte', 1), ('total_seats__lte', 80)), name='total_seats_1_80'), models.CheckConstraint(condition=models.Q(('booked_seats__lte', django.db.models.expressions.CombinedExpression(models.F('total_seats'), '-', models.F('held_seats')))), name='no_overbooking')],
            },
        ),
    ]
