# Generated by Django 5.2.17 on 2026-10-03 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_traveller_site'),
        ('operators', '0002_operatorbankaccount'),
        ('payments', '0002_razorpay_refunds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_transfer_id', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reversed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('on_hold', 'On Hold'), ('released', 'Released'), ('reversed', 'Reversed'), ('partially_reversed', 'Partially Reversed'), ('failed', 'Failed')], default='on_hold', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='bookings.booking')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='operators.operator')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='payments.payment')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_last4', models.CharField(max_length=4)),
                ('gateway_payout_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('mode', models.CharField(default='IMPS', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('reversed', 'Reversed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='queued', max_length=12)),
                ('utr', models.CharField(blank=True, default='', max_length=40)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='operators.operator')),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive')],
            },
        ),
    ]
