# Generated by Django 5.2.18 on 2026-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transfer_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
