# Generated by Django 5.2.17 on 2026-10-03 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=100)),
                ('account_number_enc', models.TextField()),
                ('account_last4', models.CharField(max_length=4)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='current', max_length=10)),
                ('pan_enc', models.TextField()),
                ('pan_last4', models.CharField(max_length=4)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('private_limited', 'Private limited')], default='proprietorship', max_length=20)),
                ('address_line', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=60)),
                ('address_state', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('razorpayx_contact_id', models.CharField(blank=True, default='', max_length=40)),
                ('razorpayx_fund_account_id', models.CharField(blank=True, default='', max_length=40)),
                ('route_account_id', models.CharField(blank=True, default='', max_length=40)),
                ('route_product_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='operators.operator')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_bank_accounts',
            },
        ),
    ]
