# Generated by Django 5.2.17 on 2026-10-04 15:56

import django.db.models.deletion
import django.utils.timezone
import operators.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operatorbankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('purpose', models.CharField(choices=[('partner_signup', 'Partner Signup'), ('operator_phone', 'Operator Phone')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'phone_otps',
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='operator',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('signup', 'Signup')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='operator',
            name='tier',
            field=models.CharField(blank=True, choices=[('', 'None'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], db_index=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='OperatorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gst', 'GST'), ('udyam', 'Udyam'), ('aadhaar', 'Aadhaar')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, storage=operators.models.private_storage, upload_to='operator-docs/')),
                ('file_type', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operators.operator')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_documents',
                'constraints': [models.UniqueConstraint(fields=('operator', 'kind'), name='one_document_per_kind')],
            },
        ),
    ]
