# Generated by Django 5.2.17 on 2026-10-05 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_operator_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('partner_signup', 'Partner Signup')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_otps',
            },
        ),
    ]
