# Generated by Django 5.2.17 on 2026-10-02 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days_before', models.PositiveSmallIntegerField()),
                ('refund_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
            ],
            options={
                'db_table': 'cancellation_rules',
                'ordering': ['-min_days_before'],
                'constraints': [models.UniqueConstraint(fields=('min_days_before', 'effective_from'), name='uniq_rule_per_day'), models.CheckConstraint(condition=models.Q(('refund_pct__gte', 0), ('refund_pct__lte', 100)), name='refund_pct_0_100')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.BigIntegerField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx')],
            },
        ),
    ]
